name: General Issue
description: General issue or question
title: "[General] "
labels: ["general"]
body:
  - type: dropdown
    id: type
    attributes:
      label: Issue Type
      options:
        - Question
        - Documentation
        - Process
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the issue or question
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any additional context, links, or references
